language: php
sudo: false
env:
  - APP_ENV=test
git:
  depth: 1
matrix:
  fast_finish: true
  include:
    - php: 7.1
#    - php: 7.2
#  allow_failures:
#    - php: 7.2
services:
  - mysql
before_install:
  - composer self-update
install:
  - cp .env.travis .env
  - composer install
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
script:
  - phpunit
notifications:
  email: khaldi.selim@gmail.com